/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_client;
import gui_client.ClientGUI;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import unoclient.UnoClient;

/**
 *
 * @author diego
 */
public class ColorSelection extends javax.swing.JFrame {

    /**
     * Creates new form selectColor
     */
    public ColorSelection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jBRed = new javax.swing.JButton();
        jBYelllow = new javax.swing.JButton();
        jBBlue = new javax.swing.JButton();
        jBGreen = new javax.swing.JButton();

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/color_pick/amarillo1.png"))); // NOI18N
        jButton4.setText("Amarillo");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setIconTextGap(-3);
        jButton4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/color_pick/amarillo2.png"))); // NOI18N
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/color_pick/amarillo0.png"))); // NOI18N
        jButton4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBRed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/color_pick/rojo1.png"))); // NOI18N
        jBRed.setText("Rojo");
        jBRed.setBorder(null);
        jBRed.setBorderPainted(false);
        jBRed.setContentAreaFilled(false);
        jBRed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBRed.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBRed.setIconTextGap(-3);
        jBRed.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/color_pick/rojo2.png"))); // NOI18N
        jBRed.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/color_pick/rojo0.png"))); // NOI18N
        jBRed.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBRed.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRedActionPerformed(evt);
            }
        });

        jBYelllow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/color_pick/amarillo1.png"))); // NOI18N
        jBYelllow.setText("Amarillo");
        jBYelllow.setBorder(null);
        jBYelllow.setBorderPainted(false);
        jBYelllow.setContentAreaFilled(false);
        jBYelllow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBYelllow.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBYelllow.setIconTextGap(-3);
        jBYelllow.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/color_pick/amarillo2.png"))); // NOI18N
        jBYelllow.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/color_pick/amarillo0.png"))); // NOI18N
        jBYelllow.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBYelllow.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBYelllow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBYelllowActionPerformed(evt);
            }
        });

        jBBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/color_pick/azul1.png"))); // NOI18N
        jBBlue.setText("Azul");
        jBBlue.setBorder(null);
        jBBlue.setBorderPainted(false);
        jBBlue.setContentAreaFilled(false);
        jBBlue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBBlue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBBlue.setIconTextGap(-3);
        jBBlue.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/color_pick/azul2.png"))); // NOI18N
        jBBlue.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/color_pick/azul0.png"))); // NOI18N
        jBBlue.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBBlue.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBlueActionPerformed(evt);
            }
        });

        jBGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/color_pick/verde1.png"))); // NOI18N
        jBGreen.setText("Verde");
        jBGreen.setToolTipText("");
        jBGreen.setBorder(null);
        jBGreen.setBorderPainted(false);
        jBGreen.setContentAreaFilled(false);
        jBGreen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBGreen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBGreen.setIconTextGap(-3);
        jBGreen.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/color_pick/verde2.png"))); // NOI18N
        jBGreen.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/color_pick/verde0.png"))); // NOI18N
        jBGreen.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBGreen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGreenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jBYelllow)
                .addGap(18, 18, 18)
                .addComponent(jBRed)
                .addGap(18, 18, 18)
                .addComponent(jBBlue)
                .addGap(18, 18, 18)
                .addComponent(jBGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jBRed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBYelllow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBBlue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBGreen, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRedActionPerformed
        try {
            // TODO add your handling code here:
            UnoClient.getUno().wildChangeColor("R");
            dispose();
        } catch (RemoteException ex) {
            Logger.getLogger(ColorSelection.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBRedActionPerformed

    private void jBBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBlueActionPerformed
        try {
            // TODO add your handling code here:
            UnoClient.getUno().wildChangeColor("B");
            dispose();
        } catch (RemoteException ex) {
            Logger.getLogger(ColorSelection.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBBlueActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jBGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGreenActionPerformed
        try {
            // TODO add your handling code here:
            UnoClient.getUno().wildChangeColor("G");
            dispose();
        } catch (RemoteException ex) {
            Logger.getLogger(ColorSelection.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBGreenActionPerformed

    private void jBYelllowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBYelllowActionPerformed
        try {
            // TODO add your handling code here:
            UnoClient.getUno().wildChangeColor("Y");
            dispose();
        } catch (RemoteException ex) {
            Logger.getLogger(ColorSelection.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jBYelllowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColorSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColorSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColorSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColorSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColorSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBlue;
    private javax.swing.JButton jBGreen;
    private javax.swing.JButton jBRed;
    private javax.swing.JButton jBYelllow;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
